// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacter(arg1, arg2) {
  return window['go']['adapters']['App']['AddCharacter'](arg1, arg2);
}

export function CloseProject() {
  return window['go']['adapters']['App']['CloseProject']();
}

export function CreateProject(arg1) {
  return window['go']['adapters']['App']['CreateProject'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['adapters']['App']['DeleteCharacter'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['adapters']['App']['DeleteProject'](arg1);
}

export function DeleteRecording(arg1) {
  return window['go']['adapters']['App']['DeleteRecording'](arg1);
}

export function ExportRecordings(arg1) {
  return window['go']['adapters']['App']['ExportRecordings'](arg1);
}

export function ExportRecordingsWithOptions(arg1) {
  return window['go']['adapters']['App']['ExportRecordingsWithOptions'](arg1);
}

export function GetAudioData(arg1) {
  return window['go']['adapters']['App']['GetAudioData'](arg1);
}

export function GetCurrentProject() {
  return window['go']['adapters']['App']['GetCurrentProject']();
}

export function GetMicrophoneGain() {
  return window['go']['adapters']['App']['GetMicrophoneGain']();
}

export function GetRecordingWaveform(arg1) {
  return window['go']['adapters']['App']['GetRecordingWaveform'](arg1);
}

export function GetSelectedDevice() {
  return window['go']['adapters']['App']['GetSelectedDevice']();
}

export function GetVideoURL() {
  return window['go']['adapters']['App']['GetVideoURL']();
}

export function ListDevices() {
  return window['go']['adapters']['App']['ListDevices']();
}

export function ListProjects() {
  return window['go']['adapters']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['adapters']['App']['OpenProject'](arg1);
}

export function RecordAudio(arg1, arg2) {
  return window['go']['adapters']['App']['RecordAudio'](arg1, arg2);
}

export function SelectDevice(arg1) {
  return window['go']['adapters']['App']['SelectDevice'](arg1);
}

export function SelectVideo() {
  return window['go']['adapters']['App']['SelectVideo']();
}

export function SetMicrophoneGain(arg1) {
  return window['go']['adapters']['App']['SetMicrophoneGain'](arg1);
}

export function StopRecording() {
  return window['go']['adapters']['App']['StopRecording']();
}

export function UpdateCharacter(arg1, arg2, arg3) {
  return window['go']['adapters']['App']['UpdateCharacter'](arg1, arg2, arg3);
}

export function UpdateProjectTitle(arg1, arg2) {
  return window['go']['adapters']['App']['UpdateProjectTitle'](arg1, arg2);
}

export function UpdateRecordingGain(arg1, arg2) {
  return window['go']['adapters']['App']['UpdateRecordingGain'](arg1, arg2);
}

export function UpdateRecordingTimecode(arg1, arg2) {
  return window['go']['adapters']['App']['UpdateRecordingTimecode'](arg1, arg2);
}

export function UpdateRecordingVolume(arg1, arg2) {
  return window['go']['adapters']['App']['UpdateRecordingVolume'](arg1, arg2);
}
