// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {adapters} from '../models';

export function AddCharacter(arg1:string,arg2:string):Promise<core.Character>;

export function CloseProject():Promise<void>;

export function CreateProject(arg1:string):Promise<core.Project>;

export function DeleteCharacter(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function ExportRecordings(arg1:string):Promise<string>;

export function ExportRecordingsWithOptions(arg1:adapters.ExportOptions):Promise<string>;

export function GetAudioData(arg1:string):Promise<string>;

export function GetCurrentProject():Promise<core.Project>;

export function GetMicrophoneGain():Promise<number>;

export function GetRecordingWaveform(arg1:string):Promise<Array<number>>;

export function GetSelectedDevice():Promise<core.DeviceInfo>;

export function GetVideoURL():Promise<string>;

export function ListDevices():Promise<Array<core.DeviceInfo>>;

export function ListProjects():Promise<Array<core.ProjectMeta>>;

export function OpenProject(arg1:string):Promise<core.Project>;

export function RecordAudio(arg1:string,arg2:number):Promise<core.Recording>;

export function SelectDevice(arg1:string):Promise<core.DeviceInfo>;

export function SelectVideo():Promise<core.Video>;

export function SetMicrophoneGain(arg1:number):Promise<void>;

export function StopRecording():Promise<void>;

export function UpdateCharacter(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateProjectTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateRecordingGain(arg1:string,arg2:number):Promise<void>;

export function UpdateRecordingTimecode(arg1:string,arg2:number):Promise<void>;

export function UpdateRecordingVolume(arg1:string,arg2:number):Promise<void>;
